# Generated by Django 4.0.5 on 2022-06-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="id_brend",
            new_name="brend",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="id_category",
            new_name="category",
        ),
    ]
